src/protected/controllers/SiteController.php
<?php

/**
 * Class SiteController
 */
class SiteController extends Controller
{
	public $defaultAction = 'login';
	/**
	 * Declares class-based actions.
	 */
	public function actions()
	{
		return array(
			// captcha action renders the CAPTCHA image displayed on the contact page
			'captcha' => array(
				'class'     => 'CCaptchaAction',
				'backColor' => 0xFFFFFF,
			),
			// page action renders "static" pages stored under 'protected/views/site/pages'
			// They can be accessed via: index.php?r=site/page&view=FileName
			'page'    => array(
				'class' => 'CViewAction',
			),
		);
	}

	/**
	 * This is the action to handle external exceptions.
	 */
	public function actionError()
	{
		if ($error = Yii::app()->errorHandler->error) {
			if (Yii::app()->request->isAjaxRequest) {
				echo $error['message'];
			} else {
				$this->render('error', $error);
			}
		}
	}


	/**
	 * Displays the login page
	 */
	public function actionLogin()
	{
		if (!Yii::app()->user->isGuest) {
			$this->redirect('/user/profile');
		}
		$model = new LoginForm;
		// if it is ajax validation request
		if ((isset($_POST['ajax']) && $_POST['ajax'] === 'login-form') || (isset($_POST['tpa']))) {
			$result = CActiveForm::validate($model);
			if (isset($_POST['tpa'])) {
				if ($result == '[]') { //without errors
					echo CJSON::encode(array('success' => "User $model->username auth successful"));
				} else {
					echo "{error:" . str_replace('LoginForm_', '', $result) . "}"; // some json
				}
				Yii::app()->end();
			}
			echo $result;
			Yii::app()->end();
		}

		// collect user input data
		if (isset($_POST['LoginForm'])) {
			$model->attributes = $_POST['LoginForm'];
			// validate user input and redirect to the previous page if valid
			if ($model->validate() && $model->login()) {
				$from = Yii::app()->request->getParam("from");
				if (self::checkReferrer()) {
					$this->redirect($from);
				}
				$this->redirect('user/profile');
			}
		}
		$this->render('login', array('model' => $model));
	}

	/**
	 * Logs out the current user and redirect to homepage.
	 */
	public function actionLogout($full = false)
	{
		//TODO: if full==true -> then destroy all sessions with username
		Yii::app()->user->logout();
		if ($this->checkReferrer()) {
			$this->redirect(Yii::app()->request->getParam("from"));
		}

		$this->redirect('login');
	}

	/**
	 * @throws CHttpException
	 */
	public function actionRegistration()
	{
		$model = new RegistrationForm;

		//ajax validate
		if (isset($_POST['ajax']) && $_POST['ajax'] === 'register-form') {
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}

		//registration
		if (isset($_POST['RegistrationForm'])) {
			$model->attributes = $_POST['RegistrationForm'];
			if ($model->validate() && $model->saveToDB()) {

				if ($model->fastUser->syncToSlowModel(null, $model->password) === true) {
					$this->_sendMail($model->fastUser, array('subject' => Yii::t('messages', 'Підтвердження користувача'), 'view' => 'confirm', 'url' => 'site/confirm'));
					Yii::app()->user->setFlash('message', Yii::t('success', 'Вам надіслано повідомлення для підтвердження email-адреси'));
					$this->redirect('/');
				} else {
					throw new CHttpException(500, Yii::t('error', 'Сталася помилка, зверніться до адміністрації.'));
				}

			}
		}
		$this->render('registration', array('model' => $model));
	}

	public function actionConfirm($login, $code)
	{

		$user = FastUser::model()->findOne(array('login' => $login));

		if (is_null($user)) {
			$message = Yii::t('error', 'Користувач з таким логіном не існує');
		} else {
			if ($user->confirm($code)) {
				Yii::app()->user->setFlash('message', Yii::t('success', 'Ваш email підтверджено'));
				$this->redirect('user/profile');
			} else {
				$message = Yii::t('error', 'Не коректний логін або код підтвердження');
			}
		}

		$this->render('confirm', array('message' => $message));
	}

	public function actionPasswordReset()
	{
		$model = new PasswordRestoreForm();
		if (isset($_POST['PasswordRestoreForm']['password'])) {
			//Post from password form
			$model->setScenario('enterPassword');
			$model->attributes = $_POST['PasswordRestoreForm'];
			if ($model->validate() && isset(Yii::app()->session['prLogin'])) {
				$user = SlowUser::model()->findById(Yii::app()->session['prLogin']);
				Yii::app()->session->clear();
				$user->password = $model->password;
				if ($user->save()) {
					Yii::app()->user->setFlash('message', Yii::t('success', 'Пароль успішно змінено'));
					$this->redirect('/');
				} else {
					$this->render('confirm', array('message' => Yii::t('error', 'Сталася помилка. Зверніться до адміністрації')));
				}
			} else {
				$this->render('passwordReset', array('model' => $model));
			}
		} elseif (isset($_POST['PasswordRestoreForm']['email'])) {
			//Post from email form
			$model->setScenario('enterEmail');
			$model->attributes = $_POST['PasswordRestoreForm'];
			if ($model->validate()) {
				$this->_sendMail($model->fastUser, array('subject' => Yii::t('messages', 'Зміна паролю'), 'view' => 'passwordReset', 'url' => 'site/passwordReset'));
				$this->render('confirm', array('message' => Yii::t('error', 'Вам відправлений лист для зміни паролю')));
			} else {
				$this->render('emailForm', array('model' => $model));
			}
		} elseif (isset($_GET['login']) && isset($_GET['code'])) {
			//Request from mail
			$login = $_GET['login'];
			$code = $_GET['code'];
			$fastUser = FastUser::model()->findOne(array('login' => $login));
			if (!is_null($fastUser) && $fastUser->checkCode($code)) {
				Yii::app()->session['prLogin'] = $login;
				$this->render('passwordReset', array("model" => $model));
			} else {
				$this->render('confirm', array('message' => Yii::t('error', 'Не коректний логін або код підтвердження')));
			}
		} else {
			//Render view to enter mail
			$this->render('emailForm', array('model' => $model));
		}
	}

	public function actionStats()
	{
		if (!isset($_GET['groups']) || !is_array($_GET['groups'])) {
			throw new CHttpException(400);
		}
		try {
			$data = Group::stats($_GET['groups']);
			echo CJSON::encode($data);
		} catch (CDbException $e) {
			throw new CHttpException(500);
		} finally {
			Yii::app()->end();
		}
	}

	public function checkReferrer()
	{
		if (!is_null($host = Yii::app()->request->getParam("from"))) {
			foreach (Yii::app()->params['allowedHosts'] as $allowed) {
				if (strpos(
						$host,
						sprintf('http://%s%s', $allowed, Yii::app()->user->identityCookie['domain']))
					!== false
				) {
					return true;
				}
			}
		}
		return false;
	}

	private function _sendMail(FastUser $fastUser, $params)
	{
		$confirmationUrl = $this->createAbsoluteUrl($params['url'], array('login' => $fastUser->login, 'code' => $fastUser->generateConfirmationCode()));
		$mailer = Yii::app()->mail;
		$message = $mailer->newMessage(array(
			'subject' => $params['subject'],
			'from'    => Yii::app()->params['notificationEmail'],
		));
		$message->view = array($params['view'], 'fullName' => $fastUser->fullName, 'confirmationUrl' => $confirmationUrl);
		$message->to = array($fastUser->email => $fastUser->fullName);
		$mailer->send($message);
	}


}

src/protected/views/site/confirm.php
<?php

$this->pageTitle = Yii::app()->name . " - Confirm"

?>

<div class="auth-container bg-white border-1 box autocenter padding-base shadow">
	<header>
		<hgroup class="usic-title">
			<div class="two-collumn bottom box">
				<div class="logo bg-usic"></div>
			</div>
			<h2 class="usic-text align-left font-lato font-60 bold cl-usic caps two-collumn bottom box">usic</h2>

			<h3 class="title-description font-18 align-center grid-top">Студентський інтернет центр НаУКМА</h3>
		</hgroup>
		<hr class="line bg-line grid-top grid-vertical">
	</header>

	<div class="form">
		<h3 class="title-description font-18 align-center grid-top"><?php echo CHtml::encode($message) ?></h3>
	</div>

	<hr class="line bg-line grid-top grid-vertical">
	<div class="link font-18 align-center">
		<a href="http://feedback.usic.at/">Зворотній зв'язок</a>
	</div>
</div>

src/protected/views/site/emailForm.php
<?php
/* @var $this SiteController */

/* @var $form CActiveForm */

$this->pageTitle = Yii::app()->name.' - Відновити пароль';
?>
<div class="auth-container bg-white border-1 box autocenter padding-base shadow">
	<header>
		<hgroup class="usic-title">
			<div class="two-collumn bottom box">
				<div class="logo bg-usic"></div>
			</div>
			<h2 class="usic-text align-left font-lato font-60 bold cl-usic caps two-collumn bottom box">usic</h2>

			<h3 class="title-description font-18 align-center grid-top">Студентський інтернет центр НаУКМА</h3>
		</hgroup>
		<hr class="line bg-line grid-top grid-vertical">
		<hgroup class="service-title">
			<h1 class="align-center font-18 cl-usic">
				<?php
				if (Yii::app()->user->hasFlash('message')) {
					echo Yii::app()->user->getFlash('message');
				}
				?>
			</h1>
		</hgroup>
	</header>

	<div class="form">

		<?php $form = $this->beginWidget('CActiveForm', array(
			'clientOptions' => array(
				'validateOnSubmit' => true,
			),
			'htmlOptions'   => array(
				'name'  => 'emailForm',
				'class' => 'auth-form'
			)

		)); ?>

		<?php echo $form->error($model, 'email'); ?>

		<?php echo $form->textField($model, 'email',
			array(
				'class'        => 'input font-22 grid-vertical box round',
				'placeholder'  => $model->getAttributeLabel('email'),
				'autocomplete' => 'off',
				'autofocus'    => 'true',
				'required'     => 'true',
				'oninvalid'    => 'setCustomValidity(\'Введіть email!\')',
				'onchange'     => 'try{setCustomValidity(\'\')}catch(e){}')
		); ?>

		<div class="grid-top align-center">
			<span class="middle box submit-block">
				<?php echo CHtml::submitButton('Відправити', array('class' => 'button submit round font-24 bg-usic cl-white')); ?>
			</span>
		</div>

		<?php $this->endWidget(); ?>
	</div>
	<!-- form -->
	<div class="registration">
		<?php echo CHtml::link('Увійти', array('/site/login')); ?>
	</div>

</div>

src/protected/views/site/error.php
<?php
/* @var $this SiteController */
/* @var $error array */

$this->pageTitle = Yii::app()->name . ' - Упс, сталась помилка';
?>
<div class="reg-container bg-white border-1 box automargin align-center padding-base shadow">
	<h2 class="cl-usic font-60"><?php echo $code; ?></h2>
	<?php if ($code == 404): ?>
		<h2 class="font-24">Сторінку не знайдено</h2>
		<hr class="line bg-line grid-top grid-vertical">
		<h3 class="font-18">Нам дуже шкода, але така сторінка не існує.</h3>
	<?php elseif ($code == 403): ?>
		<h2 class="font-24">Доступ заборонено</h2>
		<hr class="line bg-line grid-top grid-vertical">
		<h3 class="font-18">Доступ до даної ділянки сайту закрито.</h3>
	<?php else: ?>
		<h3 class="font-24">Вибачте, але сталася помилка. Ми вже працюємо над її виправленням.</h3>
		<hr class="line bg-line grid-top grid-vertical">
		<div class="grid-top font-22 link">
			<a href="http://feedback.usic.at/">Зворотній зв'язок</a>
		</div>
	<?php endif; ?>
	<a href="https://my.usic.at/">
		<div class="error404logo blue_logo bg-usic"></div>
	</a>
</div>

src/protected/views/site/login.php
<?php
/* @var $this SiteController */
/* @var $model LoginForm */
/* @var $form CActiveForm */

$this->pageTitle = Yii::app()->name . ' - Вхід';
$this->renderPartial('//layouts/meta');
?>
<div class="auth-container bg-white border-1 box autocenter padding-base shadow">
	<header>
		<hgroup class="usic-title">
			<div class="two-collumn bottom box">
				<div class="logo bg-usic"></div>
			</div>
			<h2 class="usic-text align-left font-lato font-60 bold cl-usic caps two-collumn bottom box">usic</h2>

			<h3 class="title-description font-18 align-center grid-top">Студентський інтернет центр НаУКМА</h3>
		</hgroup>
		<hr class="line bg-line grid-top grid-vertical">
		<hgroup class="service-title">
			<h1 class="align-center font-18 cl-usic">
				<?php if (Yii::app()->user->hasFlash('message')) {
					echo Yii::app()->user->getFlash('message');
				} else {
					echo "Авторизація в сервісах центру";
				} ?>
			</h1>
		</hgroup>
	</header>

	<div class="form">

		<?php $form = $this->beginWidget('CActiveForm', array(
			'clientOptions' => array(
				'validateOnSubmit' => true,
			),
			'htmlOptions'   => array(
				'name'  => 'authorization',
				'class' => 'auth-form'
			)

		)); ?>

		<?php echo $form->error($model, 'username', array('class' => 'errorMessage align-center')); ?>
		<?php echo $form->error($model, 'password', array('class' => 'errorMessage align-center')); ?>

		<?php echo $form->textField($model, 'username',
			array(
				'class'        => 'input font-22 grid-vertical box round',
				'placeholder'  => $model->getAttributeLabel('username'),
				'autocomplete' => 'off',
				'autofocus'    => 'true',
				'required'     => 'true',
				'oninvalid'    => 'setCustomValidity(\'Введіть логін!\')',
				'onchange'     => 'try{setCustomValidity(\'\')}catch(e){}')
		); ?>


		<?php echo $form->passwordField($model, 'password', array(
				'class'        => 'input font-22 box round',
				'placeholder'  => $model->getAttributeLabel('password'),
				'autocomplete' => 'off',
				'required'     => 'true',
				'oninvalid'    => 'setCustomValidity(\'Введіть пароль!\')',
				'onchange'     => 'try{setCustomValidity(\'\')}catch(e){}')
		); ?>

		<div class="grid-top">
			<span class="two-collumn middle align-left box another-computer">
				<?php echo $form->checkBox($model, 'doNotRememberMe', array('class' => 'checkbox font-24 round', 'id' => 'computer')); ?>
				<label for="computer" class="label font-18 cl-grey"
				       title="Сесія завершиться після закриття браузера"><?php echo $model->getAttributeLabel('doNotRememberMe'); ?></label>
			</span>

			<span class="two-collumn middle box submit-block">
				<?php echo CHtml::submitButton('Увійти', array('class' => 'button submit round font-24 bg-usic cl-white', 'id' => 'login')); ?>
			</span>

			<hr class="line bg-line grid-top grid-vertical">
			<div class="link font-18 inline-block">
				<?php echo CHtml::link('Відновити пароль', array('/site/passwordreset')); ?>
			</div>

			<div class="link font-18 inline-block right">
				<a href="http://feedback.usic.at/">Зворотній зв'язок</a>
			</div>
		</div>

		<?php $this->endWidget(); ?>
	</div>
	<!-- form -->
	<div class="registration font-24">
		<?php echo CHtml::link('Зареєструватись', array('/site/registration')); ?>
	</div>
</div>
<?php

Yii::app()->clientScript->registerScript('hideMessage',"$('.message').click(function(){
              $(this).animate({top: -$(this).outerHeight()}, 500);
      });");
?>

src/protected/views/site/passwordReset.php
<?php
/* @var $this SiteController */

/* @var $form CActiveForm */

$this->pageTitle = Yii::app()->name.' - Відновити пароль';
?>
<div class="auth-container bg-white border-1 box autocenter padding-base shadow">
	<header>
		<hgroup class="usic-title">
			<div class="two-collumn bottom box">
				<div class="logo bg-usic"></div>
			</div>
			<h2 class="usic-text align-left font-lato font-60 bold cl-usic caps two-collumn bottom box">usic</h2>

			<h3 class="title-description font-18 align-center grid-top">Студентський інтернет центр НаУКМА</h3>
		</hgroup>
		<hr class="line bg-line grid-top grid-vertical">
		<hgroup class="service-title">
			<h1 class="align-center font-18 cl-usic">
				<?php
				if (Yii::app()->user->hasFlash('message')) {
					echo Yii::app()->user->getFlash('message');
				}
				?>
			</h1>
		</hgroup>
	</header>

	<div class="form">

		<?php $form = $this->beginWidget('CActiveForm', array(
			'clientOptions' => array(
				'validateOnSubmit' => true,
			),
			'htmlOptions'   => array(
				'name'  => 'authorization',
				'class' => 'auth-form'
			)

		)); ?>

		<?php echo $form->error($model, 'password'); ?>
		<?php echo $form->error($model, 'repeatPassword'); ?>

		<?php echo $form->passwordField($model, 'password',
			array(
				'class'        => 'input font-22 grid-vertical box round',
				'placeholder'  => $model->getAttributeLabel('password'),
				'autocomplete' => 'off',
				'autofocus'    => 'true',
				'required'     => 'true',
				'oninvalid'    => 'setCustomValidity(\'Введіть логін!\')',
				'onchange'     => 'try{setCustomValidity(\'\')}catch(e){}')
		); ?>


		<?php echo $form->passwordField($model, 'repeatPassword', array(
				'class'        => 'input font-22 box round',
				'placeholder'  => $model->getAttributeLabel('repeatPassword'),
				'autocomplete' => 'off',
				'required'     => 'true',
				'oninvalid'    => 'setCustomValidity(\'Введіть пароль!\')',
				'onchange'     => 'try{setCustomValidity(\'\')}catch(e){}')
		); ?>

		<div class="grid-top align-center">
            <span class="middle box submit-block">
				<?php echo CHtml::submitButton('Змінити', array('class' => 'button submit round font-24 bg-usic cl-white')); ?>
			</span>
		</div>

		<?php $this->endWidget(); ?>
	</div>
	<!-- form -->


</div>

src/protected/views/site/registration.php
<?php
/* @var $this SiteController */
/* @var $model RegistrationForm */
/* @var $form CActiveForm */

$this->pageTitle = Yii::app()->name . ' - Реєстрація';

$this->renderPartial('//layouts/meta');
?>
<div class="reg-container bg-white border-1 box automargin padding-base shadow">
	<header>
		<hgroup class="usic-title">
			<div class="two-collumn bottom box">
				<div class="logo bg-usic"></div>
			</div>
			<a href="/"><h2 class="usic-text align-left font-lato font-60 bold cl-usic caps two-collumn bottom box">
					usic</h2></a>

			<h3 class="title-description font-18 align-center grid-top">Студентський інтернет центр НаУКМА</h3>
		</hgroup>
		<hr class="line bg-line grid-top grid-vertical">
		<hgroup class="service-title">
			<h1 class="align-center font-18 cl-usic">Реєстрація в сервісах центру</h1>
		</hgroup>
	</header>

	<div class="form">
		<div class="help align-center border-1 round inline-block">
			<h3 class="cl-usic"><b>Підказка:</b></h3>
			<span id="help"></span>
			<div class="link">
				<a href="http://feedback.usic.at/">Зворотній зв'язок</a>
			</div>
		</div>
		<div class="input-wrapper inline-block">
			<?php $form = $this->beginWidget('CActiveForm', array(
				'clientOptions' => array(
					'validateOnSubmit' => true,
				),
				'htmlOptions'   => array(
					'name'  => 'registration',
					'class' => 'auth-form'
				)
			)); ?>

			<?php echo $form->errorSummary($model, '','',array('class'=>'errorMessage')); ?>

			<?php echo $form->textField($model, 'login',
				array(
					'class'        => 'input font-22 grid-vertical box round',
					'placeholder'  => $model->getAttributeLabel('login'),
					'autocomplete' => 'off',
					'autofocus'    => 'true',
					'required'     => 'true',
					'oninvalid'    => 'setCustomValidity(\'Введіть логін!\')',
					'onchange'     => 'try{setCustomValidity(\'\')}catch(e){}',
					'onfocus'      => 'document.getElementById("help").innerHTML = "Латинські букви, цифри. 5 - 20 символів"'
				)
			); ?>

			<?php echo $form->passwordField($model, 'password', array(
					'class'        => 'input font-22 box round grid-bottom',
					'placeholder'  => $model->getAttributeLabel('password'),
					'autocomplete' => 'off',
					'required'     => 'true',
					'oninvalid'    => 'setCustomValidity(\'Введіть пароль!\')',
					'onchange'     => 'try{setCustomValidity(\'\')}catch(e){}',
					'onfocus'      => 'document.getElementById("help").innerHTML = "Не менше 6 символів"'
				)
			); ?>

			<?php echo $form->emailField($model, 'email',
				array(
					'class'        => 'input font-22 box round grid-bottom',
					'placeholder'  => $model->getAttributeLabel('email'),
					'autocomplete' => 'off',
					'required'     => 'true',
					'oninvalid'    => 'setCustomValidity(\'Введіть e-mail!\')',
					'onchange'     => 'try{setCustomValidity(\'\')}catch(e){}',
					'onfocus'      => 'document.getElementById("help").innerHTML = "Email, на який Вам прийде лист з підтвердженням реєстрації"'
				)
			); ?>

			<?php echo $form->textField($model, 'surName',
				array(
					'class'        => 'input font-22 box round grid-bottom',
					'placeholder'  => $model->getAttributeLabel('surName'),
					'autocomplete' => 'off',
					'required'     => 'true',
					'oninvalid'    => 'setCustomValidity(\'Введіть прізвище!\')',
					'onchange'     => 'try{setCustomValidity(\'\')}catch(e){}',
					'onfocus'      => 'document.getElementById("help").innerHTML = "Ваше прізвище кирилицею. Використовується для ідентифікації Вас як студента НаУКМА"'
				)
			); ?>

			<?php echo $form->textField($model, 'pasCode',
				array(
					'class'        => 'input font-22 box round',
					'placeholder'  => $model->getAttributeLabel('pasCode'),
					'autocomplete' => 'off',
					'required'     => 'true',
					'oninvalid'    => 'setCustomValidity(\'Введіть код перевірки!\')',
					'onchange'     => 'try{setCustomValidity(\'\')}catch(e){}',
					'onfocus'      => 'document.getElementById("help").innerHTML = "Друга буква серії та останні 3 цифри номера Вашого паспорта. Використовується для ідентифікації Вас як студента НаУКМА"'
				)
			); ?>
		</div>
		<div class="grid-top align-center">
            <span class="middle box submit-block">
                <?php echo CHtml::submitButton('Зареєструватися', array('class' => 'button submit round font-24 bg-usic cl-white')); ?>
            </span>
		</div>
		<?php $this->endWidget(); ?>
	</div>
</div>