src/protected/controllers/AdminController.php
<?php


class AdminController extends Controller
{
	public $defaultAction = 'dashboard';

	public function filters()
	{
		return array(
			'accessControl',
		);
	}

	public function accessRules()
	{
		return array(
			array(
				'allow',
				'actions' => array('dashboard', 'group', 'userUpdate', 'userSearch', 'groupAdd', 'groupRemove'),
				'expression'   => 'Yii::app()->user->inGroup("nimda")',
			),
			array(
				'deny',
				'users' => array('*'),
			),
		);
	}

	public function actionDashboard()
	{
		$data = array();
		$groups = Group::model()->findAll();
		foreach($groups as $group) {
			$data[$group->name] = Yii::app()->mongodb->users->count(array('groups' => array('$in' => array($group->name))));
		}
		$this->render('dashboard', array('data' => $data));
	}

	public function actionGroup($id)
	{
		if(Group::model()->findById($id) === false) {
			throw new CHttpException(404, 'No such group');
		}
		$dataProvider = new EMongoDataProvider('FastUser', array(
			'criteria' => array(
				'condition' => array('groups' => array('$in' => array($id))),
				'sort' => array('login' => 1)
			)
		));
		$this->render('group', array('group' => $id, 'dataProvider' => $dataProvider));
	}

	public function actionUserUpdate($id)
	{
		$model = FastUser::model()->findBy_id($id);
		if(is_null($model)) {
			throw new CHttpException(404, 'No such user');
		}

		$model->setScenario('admin');

		if (isset($_POST['FastUser'])) {
			$model->attributes = $_POST['FastUser'];
			if ($model->validate() && $model->save()) {
				if($model->syncToSlowModel()){
					Yii::app()->user->setFlash('message', 'User updated');
				} else {
					throw new CHttpException(500, "Can not sync to LDAP");
				}
			} else {
				throw new CHttpException(500, "Can not save to mongo");
			}
		}
		$this->render('userUpdate', array('model' => $model));
	}

	public function actionUserSearch()
	{
		if(!isset($_GET['login'])) {
			throw new CHttpException(400, 'Bad request');
		}
		$login = $_GET['login'];
		$user = FastUser::findByLogin($login);
		if(is_null($user)) {
			throw new CHttpException(404);
		}

		$this->redirect($this->createUrl('admin/userUpdate', array('id' => (string) $user->_id)));
	}

	public function actionGroupAdd()
	{
		if(!Yii::app()->request->getIsAjaxRequest() && (!isset($_POST['user']) || !isset($_POST['group']))) {
			throw new CHttpException(400, 'Not ajax request');
		}
		$user = $_POST['user'];
		$group = $_POST['group'];
		header('Content-Type: ' . 'application/json');
		$user = FastUser::model()->findBy_id($user);
		if(is_null($user)) {
			header('HTTP/1.1 404 No such User');
			echo CJSON::encode(array('success' => false, 'error' => 'No such user'));
		} else {
			if($user->addToGroup($group)) {
				echo CJSON::encode(array('success' => true, 'error' => 'none'));
			} else {
				header('HTTP/1.1 500 Can not add user to group');
				echo CJSON::encode(array('success' => false, 'error' => 'Can not add user to group'));
			}
		}
		Yii::app()->end();
	}

	public function actionGroupRemove()
	{
		if(!Yii::app()->request->getIsAjaxRequest() && (!isset($_POST['user']) || !isset($_POST['group']))) {
			throw new CHttpException(400, 'Not ajax request');
		}
		$user = $_POST['user'];
		$group = $_POST['group'];
		header('Content-Type: ' . 'application/json');
		$user = FastUser::model()->findBy_id($user);
		if(is_null($user)) {
			header('HTTP/1.1 404 No such User');
			echo CJSON::encode(array('success' => false, 'error' => 'No such user'));
		} else {
			if($user->removeFromGroup($group)) {
				echo CJSON::encode(array('success' => true, 'error' => 'none'));
			} else {
				header('HTTP/1.1 500 Can not remove user from group');
				echo CJSON::encode(array('success' => false, 'error' => 'Can not remove user from group'));
			}
		}
		Yii::app()->end();
	}
}

src/protected/views/admin/dashboard.php
<div class="my-container bg-white border-1 box automargin  padding-base shadow">
	<?php $this->renderPartial('//user/partials/_profileHeader'); ?>
	<div class="services_wrapper">
		<h2>View user:</h2>
		<div>
			<?php echo CHtml::beginForm('userSearch', 'get'); ?>
			<?php echo CHtml::textField('login'); ?>
			<?php echo CHtml::submitButton('View'); ?>
			<?php echo CHtml::endForm(); ?>
		</div>
		<h1>Гргупи:</h1>
		<ul>
			<?php foreach($data as $group=>$users): ?>
				<li>
					<?php echo CHtml::link($group, $this->createUrl('admin/group', array('id'=>$group))) ?> - <?php echo $users ?>
				</li>
			<?php endforeach; ?>
		</ul>
	</div>
</div>
 

src/protected/views/admin/group.php
<div class="my-container bg-white border-1 box automargin  padding-base shadow">
	<?php $this->renderPartial('//user/partials/_profileHeader'); ?>
	<div class="services_wrapper">
		<h1><?php echo CHtml::encode($group) ?></h1>

		<?php
		$this->widget('zii.widgets.grid.CGridView', array(
			'dataProvider' => $dataProvider,
			'columns' => array(
				'login:html',
				'fullName:html',
				array(
					'class' => 'CButtonColumn',
					'updateButtonUrl' => 'Yii::app()->createAbsoluteUrl("admin/userUpdate", array("id" => (string) $data->_id))',
					'template' => '{update}'
				)
			)
		));

		?>
	</div>
</div>
 

src/protected/views/admin/userUpdate.php
<div class="my-container bg-white border-1 box automargin  padding-base shadow">
	<?php $this->renderPartial('//user/partials/_profileHeader'); ?>
	<div class="services_wrapper">
		<h1><?php echo CHtml::encode($model->login) ?></h1>

		<?php $form = $this->beginWidget('CActiveForm', array(
			'clientOptions' => array(
				'validateOnSubmit' => true,
			),
			'htmlOptions'   => array(
				'name'  => 'update',
				'class' => 'auth-form'
			)
		)); ?>

		<?php echo $form->errorSummary($model, '','',array('class'=>'errorMessage')); ?>

		<?php echo $form->textField($model, 'surName',
			array(
				'class'        => 'input font-22 box round grid-bottom',
				'placeholder'  => $model->getAttributeLabel('surName'),
				'autocomplete' => 'off',
			)
		); ?>

		<?php echo $form->textField($model, 'firstName',
			array(
				'class'        => 'input font-22 box round grid-bottom',
				'placeholder'  => $model->getAttributeLabel('firstName'),
				'autocomplete' => 'off',
			)
		); ?>

		<?php echo $form->textField($model, 'middleName',
			array(
				'class'        => 'input font-22 box round grid-bottom',
				'placeholder'  => $model->getAttributeLabel('middleName'),
				'autocomplete' => 'off',
			)
		); ?>

		<?php echo $form->emailField($model, 'email',
			array(
				'class'        => 'input font-22 box round grid-bottom',
				'placeholder'  => $model->getAttributeLabel('email'),
				'autocomplete' => 'off',
			)
		); ?>

		<?php echo $form->textField($model, 'pasCode',
			array(
				'class'        => 'input font-22 box round grid-bottom',
				'placeholder'  => $model->getAttributeLabel('pasCode'),
				'autocomplete' => 'off',
			)
		); ?>

	<div class="grid-top align-center">
            <span class="middle box submit-block">
                <?php echo CHtml::submitButton('Save', array('class' => 'button submit round font-24 bg-usic cl-white')); ?>
            </span>
	</div>
	<?php $this->endWidget(); ?>

		<h2>Groups:</h2>

		<ul id="groups">
		<?php foreach($model->groups as $group): ?>
			<li>
				<span><?php echo CHtml::encode($group); ?></span>
				<?php echo CHtml::ajaxButton('Remove', $this->createUrl('admin/groupRemove'),
						array(
							'type' => 'POST',
							'data' => array(
								'group' => $group,
							    'user' => (string) $model->_id,
							    Yii::app()->request->csrfTokenName => Yii::app()->request->csrfToken
							),
							'success' => 'js: function() {
								location.reload();
							}',
							'error' => 'js: function(q, text, error) {
								alert(error);
							}'
						)
					);
				?>
			</li>
		<?php endforeach; ?>
		</ul>

		<h2>Add to group:</h2>
		<div>
			<?php echo CHtml::beginForm(); ?>
			<?php echo CHtml::textField('group'); ?>
			<?php echo CHtml::hiddenField('user', (string) $model->_id); ?>
			<?php echo CHtml::ajaxSubmitButton('Add', $this->createUrl('admin/groupAdd'),
				array(
					'type' => 'POST',
					'success' => 'js: function() {
						location.reload();
					}',
					'error' => 'js: function(q, text, error) {
						alert(error);
					}'
				)
			); ?>
			<?php echo CHtml::endForm(); ?>
		</div>
	</div>
</div>
 